# Generated by Django 4.0.2 on 2022-03-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
