# Generated by Django 4.0.2 on 2022-03-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tag_project_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main/static/Projects')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('project_title', models.CharField(db_index=True, max_length=200)),
                ('tags', models.ManyToManyField(to='main.Tag')),
            ],
        ),
        migrations.DeleteModel(
            name='Project_details',
        ),
    ]
