# Generated by Django 4.0.2 on 2022-03-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contactenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='github_urls',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='youtube_urls',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
